# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_summary',
            field=models.TextField(blank=True, verbose_name='update summary'),
        ),
        migrations.AddField(
            model_name='user',
            name='bragging_rights',
            field=models.TextField(blank=True, verbose_name='bragging rights'),
        ),
    ]
